---
version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 2.2
  pre_build:
    commands:
      - aws s3 cp s3://techspabenc/sonar-scanner-test.zip .
      - unzip sonar-scanner-test.zip
      - pwd
      - ls sonar-scanner-msbuild-4.7.1.2311-netcoreapp2.0
      - chmod +x sonar-scanner-msbuild-4.7.1.2311-netcoreapp2.0/bin
      #- PATH=./sonar*:$PATH
  build:
    commands:
      #- for lambda_func in BCP/*/Function*.cs; do cd $(dirname $lambda_func) && dotnet build && cd ../..; done
  post_build:
    commands:
      #- dotnet test BCP/BCP.sln -l:"trx;LogFileName=TestResult.trx"
    finally:
      #- mkdir -p "TestResults/$CODEBUILD_SOURCE_VERSION/$CODEBUILD_START_TIME"
      #- cd BCP; for folder in *.Tests; do for filename in $folder/*/*.trx; do cp "$filename" "../TestResults/$CODEBUILD_SOURCE_VERSION/$CODEBUILD_START_TIME/$folder.trx"; done || true; done; cd ..
artifacts:
  files:
    - '**/*'
  #discard-paths: no
  #base-directory: TestResults
